# ----
# Site
#
title: Metaideia
url: "http://metaideia.com.br"
baseurl:
google_analytics_key:
disqus_shortname:
facebook: metaideia
instagram: metaideia

navigation:
  - name: Home
    link: /
  - name: Sobre
    link: /sobre/
  - name: Contato
    link: /contato/

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/author.jpg
description: Se alimentar diariamente das ideias que precisam fazer parte do seu mindset é a única maneira de garantir o seu sucesso.

# -----
# Build
#
paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      push_sidebar_down: true
      comments: true
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
